Categorical -> numerical (Ordinal.OHE,Target encoding,frequency encoding)
\n Discretization(binning)
\n target feature -> label encoding , label binarizer , multi label binarizar(to encode target col)

In [68]:
import numpy as np
import pandas as pd

In [69]:
df = pd.read_csv('customers.csv')

In [70]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

### 1. Ordinal Encoding

In [71]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [72]:
X_train, X_test , y_train, y_test = train_test_split(df.iloc[:,2:4],df.iloc[:,-1],test_size=0.2)

In [73]:
X_train.head()

     review education
5   Average    School
39     Poor        PG
38     Good    School
17     Poor        UG
14     Poor        PG

In [74]:
# specify order
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [75]:
X_train = oe.fit_transform(X_train)
X_test =oe.transform(X_test)

In [76]:
X_train

array([[1., 0.],
       [0., 2.],
       [2., 0.],
       [0., 1.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [1., 2.],
       [2., 2.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [2., 1.],
       [1., 1.],
       [1., 2.],
       [1., 0.],
       [2., 0.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [2., 2.],
       [0., 2.],
       [2., 1.],
       [2., 1.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [0., 1.],
       [2., 2.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [2., 0.],
       [0., 2.]])

In [77]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [78]:
oe.feature_names_in_

array(['review', 'education'], dtype=object)

In [79]:
oe.n_features_in_

2

In [80]:
oe.inverse_transform(np.array([2,1]).reshape(1,2))

array([['Good', 'UG']], dtype=object)

In [81]:
oe.get_feature_names_out()

array(['review', 'education'], dtype=object)

In [82]:
# Handling unknown
# set unknown 
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']],
                    handle_unknown='use_encoded_value',
                    unknown_value=-1
                    )
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,2:4], df.iloc[:,-1], test_size=0.2)
X_train = oe.fit_transform(X_train)
oe.transform(np.array(['Poor','college']).reshape(1,2))

/opt/anaconda3/envs/ml-env/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[ 0., -1.]])

### 2. Rare Categories

In [83]:
# handling infrequent categories
X = np.array([['dog']*5 + ['cat']*20 + ['rabbit']*10 + ['snake']*3 + ['horse']*2],dtype=object).T

In [84]:
X

array([['dog'],
       ['dog'],
       ['dog'],
       ['dog'],
       ['dog'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['snake'],
       ['snake'],
       ['snake'],
       ['horse'],
       ['horse']], dtype=object)

In [85]:
enc = OrdinalEncoder(max_categories=3).fit(X)

In [86]:
enc.infrequent_categories_

[array(['dog', 'horse', 'snake'], dtype=object)]

In [87]:
enc.transform(np.array(['cat','rabbit','horse','snake']).reshape(4,1))

array([[0.],
       [1.],
       [2.],
       [2.]])

In [88]:
enc = OrdinalEncoder(min_frequency=4).fit(X)

In [89]:
enc.infrequent_categories_

[array(['horse', 'snake'], dtype=object)]

In [90]:
enc.transform(np.array([['cat','rabbit','snake','dog','horse']]).reshape(5,1))

array([[0.],
       [2.],
       [3.],
       [1.],
       [3.]])

In [91]:
# handling missing data 

# Eg.
data = [['Cat'],[np.nan],['Dog'],[np.nan],['Horse'],['Rabbit']]

encoder = OrdinalEncoder(encoded_missing_value=-1)

encoded_data = encoder.fit_transform(data)

print(encoded_data)

[[ 0.]
 [-1.]
 [ 1.]
 [-1.]
 [ 2.]
 [ 3.]]

### Label Encoder

It is not a feature(input cols) encoding technique, its a target col encoding technique

In [92]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [93]:
X_train, X_test , y_train, y_test = train_test_split(df.iloc[:,2:4],df.iloc[:,-1],test_size=0.2)

In [94]:
from sklearn.preprocessing import LabelEncoder

In [95]:
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [96]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [97]:
le.inverse_transform(np.array([1,1,0]))

array(['Yes', 'Yes', 'No'], dtype=object)

### 2. One Hot Encoder

In [98]:
cars = pd.read_csv('cars.csv').drop(columns=['km_driven','owner'])
cars.head()

     brand    fuel  selling_price
0   Maruti  Diesel         450000
1    Skoda  Diesel         370000
2    Honda  Petrol         158000
3  Hyundai  Diesel         225000
4   Maruti  Petrol         130000

In [99]:
X = cars.iloc[:,0:2]
y= cars.iloc[:,-1]

In [100]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [101]:
X_train['fuel'].nunique()

4

In [102]:
from sklearn.preprocessing import OneHotEncoder

In [103]:
ohe = OneHotEncoder()

In [104]:
ohe.fit_transform(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 16256 stored elements and shape (8128, 36)>

We can also use .toarray() fxn to convert it to pandas df

In [105]:
X_train = ohe.fit_transform(X_train).toarray()
X_train

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [106]:
X_train.shape

(6502, 36)

In [107]:
ohe.categories_

[array(['Ambassador', 'Ashok', 'Audi', 'BMW', 'Chevrolet', 'Daewoo',
        'Datsun', 'Fiat', 'Force', 'Ford', 'Honda', 'Hyundai', 'Isuzu',
        'Jaguar', 'Jeep', 'Kia', 'Land', 'Lexus', 'MG', 'Mahindra',
        'Maruti', 'Mercedes-Benz', 'Mitsubishi', 'Nissan', 'Opel',
        'Peugeot', 'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen',
        'Volvo'], dtype=object),
 array(['CNG', 'Diesel', 'LPG', 'Petrol'], dtype=object)]

In [108]:
ohe.feature_names_in_

array(['brand', 'fuel'], dtype=object)

In [109]:
ohe.n_features_in_

2

In [110]:
ohe.get_feature_names_out()

array(['brand_Ambassador', 'brand_Ashok', 'brand_Audi', 'brand_BMW',
       'brand_Chevrolet', 'brand_Daewoo', 'brand_Datsun', 'brand_Fiat',
       'brand_Force', 'brand_Ford', 'brand_Honda', 'brand_Hyundai',
       'brand_Isuzu', 'brand_Jaguar', 'brand_Jeep', 'brand_Kia',
       'brand_Land', 'brand_Lexus', 'brand_MG', 'brand_Mahindra',
       'brand_Maruti', 'brand_Mercedes-Benz', 'brand_Mitsubishi',
       'brand_Nissan', 'brand_Opel', 'brand_Peugeot', 'brand_Renault',
       'brand_Skoda', 'brand_Tata', 'brand_Toyota', 'brand_Volkswagen',
       'brand_Volvo', 'fuel_CNG', 'fuel_Diesel', 'fuel_LPG',
       'fuel_Petrol'], dtype=object)

In [111]:
pd.DataFrame(X_train,columns=ohe.get_feature_names_out())

,brand_Ambassador,brand_Ashok,brand_Audi,brand_BMW,brand_Chevrolet,brand_Daewoo,brand_Datsun,brand_Fiat,brand_Force,brand_Ford,...,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_Volvo,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6497,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6498,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6499,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
6500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6501,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [112]:
# we can use ohe.inverse_transform() as well

In [113]:
# drop 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

ohe = OneHotEncoder(drop='first',sparse_output=False)
ohe.fit_transform(X_train).shape

(6502, 34)

In [114]:
ohe.drop_idx_

array([0, 0], dtype=object)

In [115]:
# handling rare categories
X_train['brand'].value_counts()

brand
Maruti           1953
Hyundai          1127
Mahindra          635
Tata              586
Toyota            391
Honda             369
Ford              320
Chevrolet         185
Renault           183
Volkswagen        154
BMW                96
Skoda              82
Nissan             62
Jaguar             59
Volvo              54
Datsun             48
Mercedes-Benz      43
Fiat               35
Audi               30
Jeep               26
Lexus              22
Mitsubishi         13
Force               6
Land                5
Kia                 4
Ambassador          3
MG                  3
Daewoo              3
Isuzu               2
Ashok               1
Peugeot             1
Opel                1
Name: count, dtype: int64

In [116]:
cars['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [117]:
# using min_frequency

ohe = OneHotEncoder(sparse_output=False,min_frequency=100)
ohe.fit_transform(X_train).shape

(6502, 14)

In [118]:
ohe.get_feature_names_out()

array(['brand_Chevrolet', 'brand_Ford', 'brand_Honda', 'brand_Hyundai',
       'brand_Mahindra', 'brand_Maruti', 'brand_Renault', 'brand_Tata',
       'brand_Toyota', 'brand_Volkswagen', 'brand_infrequent_sklearn',
       'fuel_Diesel', 'fuel_Petrol', 'fuel_infrequent_sklearn'],
      dtype=object)

In [119]:
# using max categories

ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore',max_categories=15)
ohe.fit_transform(X_train).shape

(6502, 19)

In [120]:
ohe.get_feature_names_out()

array(['brand_BMW', 'brand_Chevrolet', 'brand_Ford', 'brand_Honda',
       'brand_Hyundai', 'brand_Jaguar', 'brand_Mahindra', 'brand_Maruti',
       'brand_Nissan', 'brand_Renault', 'brand_Skoda', 'brand_Tata',
       'brand_Toyota', 'brand_Volkswagen', 'brand_infrequent_sklearn',
       'fuel_CNG', 'fuel_Diesel', 'fuel_LPG', 'fuel_Petrol'], dtype=object)

In [121]:
# handling unkonwn categories
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
ohe.fit_transform(X_train)

ohe.transform(np.array(['local','Petrol']).reshape(1,2))

/opt/anaconda3/envs/ml-env/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1.]])

###  Label Binarizer

Used for the X_test or target columns

In [122]:
from sklearn.preprocessing import LabelBinarizer

# Sample target variable for a multi-class classification problem
y = ['cat', 'dog', 'fish', 'dog', 'cat']

# Initialize the LabelBinarizer
lb = LabelBinarizer()

# Fit and transform the target variable
y_binarized = lb.fit_transform(y)

print("Binarized labels:\n", y_binarized)

# Inverse transform to recover original labels
y_original = lb.inverse_transform(y_binarized)

print("Original labels:\n", y_original)

Binarized labels:
 [[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]]
Original labels:
 ['cat' 'dog' 'fish' 'dog' 'cat']

In [123]:
from sklearn.preprocessing import MultiLabelBinarizer

# Example multi-label data
y = [('red', 'blue'), ('blue', 'green'), ('green',), ('red',)]

# Initialize MultiLabelBinarizer
mlb = MultiLabelBinarizer()

# Fit and transform the data to binary matrix format
Y = mlb.fit_transform(y)

print("Binary matrix:\n", Y)
print("Class labels:", mlb.classes_)

# Inverse transform to recover original labels
y_inv = mlb.inverse_transform(Y)
print("Inverse transformed labels:", y_inv)

Binary matrix:
 [[1 0 1]
 [1 1 0]
 [0 1 0]
 [0 0 1]]
Class labels: ['blue' 'green' 'red']
Inverse transformed labels: [('blue', 'red'), ('blue', 'green'), ('green',), ('red',)]

## Session 2

In [124]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split

In [125]:
df = pd.read_csv("cars.csv")
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [126]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

## The Hard Way

In [127]:
X_train,X_test,y_train,y_test = train_test_split(
    df.drop(columns=['selling_price']),
    df['selling_price'],
    test_size=0.2,
    random_state=42
)

In [128]:
# apply ordinal encoder to owner
oe = OrdinalEncoder(categories=[['Test Drive Car', 'Fourth & Above Owner', 'Third Owner', 'Second Owner', 'First Owner']])

X_train_owner = oe.fit_transform(X_train.loc[:,['owner']])
X_test_owner = oe.transform(X_test.loc[:,['owner']])

In [129]:
# convert to df 
X_train_owner_df = pd.DataFrame(X_train_owner,columns=oe.get_feature_names_out())
X_test_owner_df = pd.DataFrame(X_test_owner,columns=oe.get_feature_names_out())

In [130]:
X_train_owner_df

      owner
0       4.0
1       3.0
2       1.0
3       3.0
4       4.0
...     ...
6497    4.0
6498    3.0
6499    4.0
6500    4.0
6501    3.0

[6502 rows x 1 columns]

In [131]:
ohe = OneHotEncoder(sparse_output=False)

X_train_brand_fuel = ohe.fit_transform(X_train[['brand','fuel']])
X_test_brand_fuel = ohe.transform(X_test[['brand','fuel']])

In [132]:
oe.get_feature_names_out()

array(['owner'], dtype=object)

In [134]:
# Converting to dataframe
X_train_brand_fuel_df = pd.DataFrame(X_train_brand_fuel,columns=ohe.get_feature_names_out())
X_test_brand_fuel_df = pd.DataFrame(X_test_brand_fuel,columns=ohe.get_feature_names_out())

In [135]:
X_train_rem = X_train.drop(columns=['brand','fuel','owner'],inplace=True)
X_test_rem = X_test.drop(columns=['brand','fuel','owner'],inplace=True)

In [136]:
X_train = pd.concat([X_train_rem,X_train_owner_df,X_train_brand_fuel_df],axis=1)
X_test = pd.concat([X_test_rem,X_test_owner_df,X_test_brand_fuel_df],axis=1)

In [137]:
X_train.head()

,owner,brand_Ambassador,brand_Ashok,brand_Audi,brand_BMW,brand_Chevrolet,brand_Daewoo,brand_Datsun,brand_Fiat,brand_Force,...,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_Volvo,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

## The Easy Way!

In [138]:
from sklearn.compose import ColumnTransformer

df = pd.read_csv('cars.csv')

X_train,X_test,y_train,y_test = train_test_split(
    df.drop(columns=['selling_price']),
    df['selling_price'],
    test_size=0.2,
    random_state=42
)

X_train.head()

        brand  km_driven    fuel                 owner
6518     Tata       2560  Petrol           First Owner
6144    Honda      80000  Petrol          Second Owner
6381  Hyundai     150000  Diesel  Fourth & Above Owner
438    Maruti     120000  Diesel          Second Owner
5939   Maruti      25000  Petrol           First Owner

In [142]:
transformer = ColumnTransformer([

    ("ordinal", OrdinalEncoder(categories=[['Test Drive Car','Fourth & Above Owner', 'Third Owner', 'Second Owner', 'First Owner']]), ['owner']),
    ("onehot", OneHotEncoder(handle_unknown='ignore', sparse_output=False), ['brand','fuel'])
],
    remainder='passthrough'
)

# setting to pandas df
transformer.set_output(transform='pandas')

ColumnTransformer(remainder='passthrough',
                  transformers=[('ordinal',
                                 OrdinalEncoder(categories=[['Test Drive Car',
                                                             'Fourth & Above '
                                                             'Owner',
                                                             'Third Owner',
                                                             'Second Owner',
                                                             'First Owner']]),
                                 ['owner']),
                                ('onehot',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 ['brand', 'fuel'])])