# Count Encoder/Frequency Encoder

In [1]:
# dataset generation
import pandas as pd
import numpy as np
import category_encoders as ce

from Feature_Engineering.FeatureEncoding1 import X_train, y_train, y_test, encoder

# Simulating a dataset
data = {
    'Age': np.random.randint(20, 60, size=100).astype(float),  # Random ages between 20 and 60
    'State': np.random.choice(['Karnataka', 'Tamil Nadu', 'Maharashtra', 'Delhi', 'Telangana'], size=100),
    'Education': np.random.choice(['High School', 'UG', 'PG'], size=100),
    'Package': np.random.rand(100) * 100  # Random package values for demonstration
}

# Introducing missing values in 'Age' column (5%)
np.random.seed(0)  # For reproducibility
missing_indices = np.random.choice(data['Age'].shape[0], replace=False, size=int(data['Age'].shape[0] * 0.05))
data['Age'][missing_indices] = np.nan

df = pd.DataFrame(data)

df.head()

    Age       State    Education    Package
0  58.0   Telangana           UG  52.009899
1  41.0   Karnataka           UG  52.172435
2   NaN       Delhi           PG  19.857098
3  59.0       Delhi  High School  62.529099
4  21.0  Tamil Nadu           UG  29.574033

In [2]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns='Package'), df['Package'], test_size=0.2, random_state=41)

In [3]:
X_train.head()

     Age       State    Education
86   NaN   Karnataka  High School
48  58.0  Tamil Nadu           UG
49  30.0       Delhi           PG
99  53.0   Karnataka           UG
41  41.0   Telangana  High School

In [4]:
X_train['State'].value_counts()

State
Karnataka      23
Telangana      19
Delhi          16
Tamil Nadu     13
Maharashtra     9
Name: count, dtype: int64

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.base import BaseEstimator,TransformerMixin
import pandas as pd
import numpy as np
import sklearn

In [6]:
# using category_encoders
from category_encoders import CountEncoder

In [12]:
preprocessor = ColumnTransformer(
    transformers=[
        ('age_missing',SimpleImputer(strategy='mean'),['Age']),
        ('cat_state',CountEncoder(normalize=True),['State']),# if normalize=False , then it behaves as Count encoder
        ('education',OrdinalEncoder(),['Education']),
    ]
)
sklearn.set_config(transform_output="pandas")

In [13]:
preprocessor.fit_transform(X_train)

    age_missing__Age  cat_state__State  education__Education
86         39.947368            0.2875                   0.0
48         58.000000            0.1625                   2.0
49         30.000000            0.2000                   1.0
99         53.000000            0.2875                   2.0
41         41.000000            0.2375                   0.0
..               ...               ...                   ...
65         23.000000            0.1625                   0.0
80         24.000000            0.2875                   2.0
12         27.000000            0.1125                   2.0
35         38.000000            0.1625                   0.0
64         56.000000            0.2875                   2.0

[80 rows x 3 columns]

In [14]:
# frequency encoding

In [15]:
# parameters
import pandas as pd
import numpy as np
import category_encoders as ce

# Simulating a dataset
np.random.seed(42)  # For reproducibility
data = {
    'State': np.random.choice(['Karnataka', 'Tamil Nadu', 'Maharashtra', 'Delhi', 'Telangana', np.NaN], size=100),
    'Education': np.random.choice(['High School', 'UG', 'PG', np.NaN], size=100)
}
df = pd.DataFrame(data)

df.head(25)

          State    Education
0         Delhi           PG
1     Telangana  High School
2   Maharashtra  High School
3     Telangana  High School
4     Telangana           PG
5    Tamil Nadu  High School
6   Maharashtra          nan
7   Maharashtra  High School
8   Maharashtra          nan
9     Telangana          nan
10        Delhi          nan
11  Maharashtra           PG
12          nan           PG
13    Telangana           PG
14   Tamil Nadu  High School
15        Delhi          nan
16          nan           PG
17          nan           PG
18   Tamil Nadu  High School
19        Delhi           PG
20    Telangana  High School
21    Karnataka           UG
22        Delhi           PG
23   Tamil Nadu           UG
24          nan  High School

In [16]:
df.isnull().sum()

State        0
Education    0
dtype: int64

In [18]:
# Initialize the CountEncoder with various parameters
encoder = ce.CountEncoder(
    cols=['State', 'Education'],
    handle_missing='value',
    handle_unknown='value',
)

In [19]:
encoder.fit_transform(df)

    State  Education
0      25         34
1      17         27
2      11         27
3      17         27
4      17         34
..    ...        ...
95     25         27
96     25         16
97     17         23
98     11         23
99     17         23

[100 rows x 2 columns]

In [20]:
encoder.mapping

{'State': State
 Delhi          25
 Tamil Nadu     19
 Telangana      17
 nan            17
 Maharashtra    11
 Karnataka      11
 Name: count, dtype: int64,
 'Education': Education
 PG             34
 High School    27
 nan            23
 UG             16
 Name: count, dtype: int64}

In [21]:
np.random.seed(0)  # For reproducibility
data = {
    'Category': np.random.choice(['A', 'B', 'C', 'D', 'E', 'F', np.nan], size=100, p=[0.3, 0.25, 0.15, 0.15, 0.05, 0.05, 0.05]),
    'Value': np.random.rand(100)
}

df = pd.DataFrame(data)

df.sample(10)

   Category     Value
91        C  0.209844
29        B  0.290078
2         C  0.735194
50        C  0.149448
44        C  0.806194
78        A  0.704414
33        C  0.298282
65        B  0.855803
75        A  0.223925
45        C  0.703889

In [22]:
df['Category'].value_counts()

Category
A      34
B      22
C      21
D      12
nan     5
F       4
E       2
Name: count, dtype: int64

In [23]:
encoder = ce.CountEncoder(
    cols=['Category'],
    min_group_size=10,  # Groups with counts less than 5 will be combined
    min_group_name='salman',  # Use default naming for combined minimum groups
)

# Fit and transform the dataset
encoded_df = encoder.fit_transform(df['Category'])

# Display the original and encoded data for comparison
df['Encoded'] = encoded_df
print(df.head(20))

   Category     Value  Encoded
0         B  0.677817       22
1         D  0.270008       12
2         C  0.735194       21
3         B  0.962189       22
4         B  0.248753       22
5         C  0.576157       21
6         B  0.592042       22
7         E  0.572252       11
8       nan  0.223082       11
9         B  0.952749       22
10        D  0.447125       12
11        B  0.846409       22
12        C  0.699479       21
13        F  0.297437       11
14        A  0.813798       34
15        A  0.396506       34
16        A  0.881103       34
17        D  0.581273       12
18        D  0.881735       12
19        E  0.692532       11

In [24]:
encoder.mapping

{'Category': Category
 A         34
 B         22
 C         21
 D         12
 salman    11
 Name: count, dtype: int64}

# Binary Encoder

In [25]:
import pandas as pd
import category_encoders as ce

# Sample dataset
data = {
    'Item': ['Item1', 'Item2', 'Item3', 'Item4', 'Item5', 'Item6', 'Item7', 'Item8'],
    'Fruit': ['Apple', 'Banana', 'Cherry', 'Date', 'Elderberry', 'Fig', 'Grape', 'Honeydew']
}
df = pd.DataFrame(data)

df

    Item       Fruit
0  Item1       Apple
1  Item2      Banana
2  Item3      Cherry
3  Item4        Date
4  Item5  Elderberry
5  Item6         Fig
6  Item7       Grape
7  Item8    Honeydew

In [26]:
encoder = ce.BinaryEncoder(cols=["Fruit"],return_df=True)

df_encoded = encoder.fit_transform(df)
print(df_encoded)

    Item  Fruit_0  Fruit_1  Fruit_2  Fruit_3
0  Item1        0        0        0        1
1  Item2        0        0        1        0
2  Item3        0        0        1        1
3  Item4        0        1        0        0
4  Item5        0        1        0        1
5  Item6        0        1        1        0
6  Item7        0        1        1        1
7  Item8        1        0        0        0

# Target Encoder

In [27]:
# using category_encoder

import pandas as pd
import category_encoders as ce

# Sample data
data = {
    'Feature': ['A', 'B', 'A', 'B', 'C', 'A', 'B', 'C'],
    'Target': [1, 0, 0, 1, 1, 1, 0, 1]
}
df = pd.DataFrame(data)

# Separating the feature and target columns
X = df.drop('Target', axis=1)
y = df['Target']

# Initialize the TargetEncoder
encoder = ce.TargetEncoder(cols=['Feature'])

# Fit the encoder using the feature data and target variable
encoder.fit(X, y)

# Transform the data
encoded = encoder.transform(X)

# Show the original and encoded data
print(pd.concat([df, encoded], axis=1))

   Feature  Target   Feature
0        A       1  0.631436
1        B       0  0.579948
2        A       0  0.631436
3        B       1  0.579948
4        C       1  0.678194
5        A       1  0.631436
6        B       0  0.579948
7        C       1  0.678194

In [28]:
encoder.mapping

{'Feature': Feature
  1    0.631436
  2    0.579948
  3    0.678194
 -1    0.625000
 -2    0.625000
 dtype: float64}